/**
 * "Start with Windows" for the control API.
 *
 * Implemented as one .vbs launcher in the per-user Startup folder rather than a
 * Run-key entry or a scheduled task, because:
 *   - WScript.Shell.Run(cmd, 0, False) is the only dependency-free way to give
 *     node.exe a console that *starts* hidden. The window still exists, so the
 *     tray helper can reveal it later; CREATE_NO_WINDOW-style launches cannot.
 *   - A file in shell:startup needs no elevation (schtasks /SC ONLOGON does)
 *     and the user can inspect or delete it by hand.
 *
 * The file is written as UTF-16LE with a BOM: wscript only reads a .vbs as
 * Unicode when that BOM is present, and install paths routinely contain
 * non-ASCII characters.
 *
 * Every function takes an explicit `startupDir` so tests can point it at a
 * temporary folder; callers normally rely on the APPDATA-based default.
 */

import fs from 'node:fs'
import path from 'node:path'

const IS_WIN = process.platform === 'win32'
const ENTRY_FILE = 'Microsoft-Rewards-Script.vbs'
const MARKER_PREFIX = "' mrs-autostart: "
const HOST_PATTERN = /^[A-Za-z0-9._:[\]-]+$/

// wscript only reads a .vbs as Unicode when the file starts with a UTF-16LE BOM.
const BOM = '\ufeff'

function badRequest(message) {
    return Object.assign(new Error(message), { code: 'BAD_REQUEST' })
}

function startupDirUnavailableReason() {
    return IS_WIN
        ? 'APPDATA is not set, so the Startup folder could not be located.'
        : `Start with Windows is only available on Windows (this host runs ${process.platform}).`
}

export function defaultStartupDir(sourceEnv = process.env) {
    if (!IS_WIN) return null
    const appData = sourceEnv.APPDATA
    if (!appData) return null
    return path.join(appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup')
}

export function autostartEntryPath(startupDir) {
    return startupDir ? path.join(startupDir, ENTRY_FILE) : null
}

function decodeLauncher(buffer) {
    if (buffer.length >= 2 && buffer[0] === 0xff && buffer[1] === 0xfe) {
        return buffer.subarray(2).toString('utf16le')
    }
    return buffer.toString('utf8')
}

/**
 * The marker comment inside the launcher, or null when the file was not written
 * by this feature. A corrupt marker still identifies the file as ours ({}), so
 * disabling can clean it up.
 */
function readMarker(text) {
    for (const line of text.split(/\r?\n/)) {
        if (!line.startsWith(MARKER_PREFIX)) continue
        try {
            const parsed = JSON.parse(line.slice(MARKER_PREFIX.length))
            if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) return parsed
        } catch {}
        return {}
    }
    return null
}

/** Windows command-line quoting. Paths cannot contain `"`, so wrapping is enough. */
function quoteArg(value) {
    const text = String(value)
    if (text.includes('"')) throw badRequest(`Path contains a double quote and cannot be launched: ${text}`)
    return `"${text}"`
}

/** VBS string literal: inner quotes are escaped by doubling them. */
function vbsLiteral(value) {
    const text = String(value)
    if (/[\r\n]/.test(text)) throw badRequest(`Path contains a line break and cannot be launched: ${text}`)
    return `"${text.replace(/"/g, '""')}"`
}

export function normalizeTarget({ projectRoot, serverEntry, nodePath = process.execPath, host, port }) {
    if (!projectRoot) throw badRequest('projectRoot is required.')
    if (!serverEntry) throw badRequest('serverEntry is required.')

    const resolvedHost = String(host ?? '127.0.0.1')
    if (!HOST_PATTERN.test(resolvedHost)) throw badRequest(`Refusing to write autostart for host "${resolvedHost}".`)

    const resolvedPort = Number(port)
    if (!Number.isSafeInteger(resolvedPort) || resolvedPort < 1 || resolvedPort > 65535) {
        throw badRequest(`Refusing to write autostart for port "${port}".`)
    }

    return {
        nodePath: path.resolve(nodePath),
        serverEntry: path.resolve(serverEntry),
        projectRoot: path.resolve(projectRoot),
        host: resolvedHost,
        port: resolvedPort
    }
}

export function buildCommandLine(target) {
    return [
        quoteArg(target.nodePath),
        quoteArg(target.serverEntry),
        '--hidden',
        '--host',
        target.host,
        '--port',
        String(target.port)
    ].join(' ')
}

export function renderLauncher(target) {
    const commandLine = buildCommandLine(target)
    return [
        "' Microsoft-Rewards-Script - Start with Windows",
        "'",
        "' Generated by the control API (the Startup toggle in the Web UI, or [w]",
        "' in the terminal panel). Deleting this file turns autostart off.",
        "'",
        "' Window style 0 keeps the console hidden at logon. The window still",
        "' exists, so the tray icon can bring the terminal back.",
        `${MARKER_PREFIX}${JSON.stringify(target)}`,
        'Set shell = CreateObject("WScript.Shell")',
        `shell.CurrentDirectory = ${vbsLiteral(target.projectRoot)}`,
        `shell.Run ${vbsLiteral(commandLine)}, 0, False`,
        ''
    ].join('\r\n')
}

function samePath(a, b) {
    return path.normalize(String(a ?? '')).toLowerCase() === path.normalize(String(b ?? '')).toLowerCase()
}

function sameTarget(marker, target) {
    if (!marker || !target) return false
    return (
        samePath(marker.nodePath, target.nodePath) &&
        samePath(marker.serverEntry, target.serverEntry) &&
        samePath(marker.projectRoot, target.projectRoot) &&
        String(marker.host ?? '') === target.host &&
        Number(marker.port) === target.port
    )
}

/**
 * Current autostart state. `stale` means an entry exists but launches a
 * different install, host, or port than the server asking the question - the
 * usual cause is a moved or copied project folder. Re-enabling rewrites it.
 */
export function getAutostartStatus({ startupDir = defaultStartupDir(), target = null } = {}) {
    if (!startupDir) {
        return {
            supported: false,
            enabled: false,
            managed: false,
            stale: false,
            path: null,
            entry: null,
            reason: startupDirUnavailableReason()
        }
    }

    const filePath = autostartEntryPath(startupDir)
    let buffer
    try {
        buffer = fs.readFileSync(filePath)
    } catch (error) {
        if (error.code === 'ENOENT') {
            return { supported: true, enabled: false, managed: false, stale: false, path: filePath, entry: null }
        }
        return {
            supported: true,
            enabled: false,
            managed: false,
            stale: false,
            path: filePath,
            entry: null,
            reason: `Could not read the Startup entry: ${error.message}`
        }
    }

    const marker = readMarker(decodeLauncher(buffer))
    return {
        supported: true,
        enabled: true,
        managed: marker !== null,
        stale: Boolean(target) && !sameTarget(marker, target),
        path: filePath,
        entry: marker && Object.keys(marker).length ? marker : null
    }
}

export function enableAutostart({ startupDir = defaultStartupDir(), ...targetInput } = {}) {
    if (!startupDir) throw badRequest(startupDirUnavailableReason())

    const target = normalizeTarget(targetInput)
    const contents = renderLauncher(target)
    const filePath = autostartEntryPath(startupDir)
    const tmpPath = `${filePath}.tmp`

    try {
        fs.mkdirSync(startupDir, { recursive: true })
        // Write-then-rename so a crash mid-write cannot leave a half-written
        // launcher that fails silently at the next logon.
        fs.writeFileSync(tmpPath, Buffer.from(BOM + contents, 'utf16le'))
        fs.renameSync(tmpPath, filePath)
    } catch (error) {
        try {
            fs.rmSync(tmpPath, { force: true })
        } catch {}
        throw Object.assign(new Error(`Could not write the Startup entry: ${error.message}`), { code: 'WRITE_FAILED' })
    }

    return { supported: true, enabled: true, managed: true, stale: false, path: filePath, entry: target }
}

export function disableAutostart({ startupDir = defaultStartupDir() } = {}) {
    if (!startupDir) throw badRequest(startupDirUnavailableReason())

    const filePath = autostartEntryPath(startupDir)
    let buffer
    try {
        buffer = fs.readFileSync(filePath)
    } catch (error) {
        if (error.code === 'ENOENT') {
            return { supported: true, enabled: false, managed: false, stale: false, path: filePath, entry: null }
        }
        throw Object.assign(new Error(`Could not read the Startup entry: ${error.message}`), { code: 'WRITE_FAILED' })
    }

    // Never delete a same-named file this feature did not create. (Enabling
    // does overwrite it: that is an explicit "manage this from now on".)
    if (readMarker(decodeLauncher(buffer)) === null) {
        throw Object.assign(
            new Error(`${filePath} was not created by this app - remove it by hand if you no longer want it.`),
            { code: 'CONFLICT' }
        )
    }

    try {
        fs.rmSync(filePath, { force: true })
    } catch (error) {
        throw Object.assign(new Error(`Could not remove the Startup entry: ${error.message}`), { code: 'WRITE_FAILED' })
    }

    return { supported: true, enabled: false, managed: false, stale: false, path: filePath, entry: null }
}
